### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by lukehinds** [pgooch/github-repo-list#1]
Hi,

I took a look at your plugin. Just a friendly tip, you should include what sort of formatting people need to use for the attributes such as username etc. Most people don't know code very well, and so will need some help there. 

The only one shown is [github-repo-list] 

Regards 
Luke

**Comment by pgooch** [comment]
Yeah, thats a good point. I was planning on making a round a wordpress
plugin updates once I finish up a couple other projects. I'll make sure to
add a complete example in the help section so people can copy/paste and
edit. Thanks.

_Phillip Gooch_
_425-268-0162_

**Comment by pgooch** [comment]
An example shortcode has been added to the help tab contents.
